version: '3.8'

services:
  security.api:
    build:
      context: .
      dockerfile: SecurityDomain/SecurityAPI/Dockerfile
    container_name: security-api
    ports:
      - "5003:80"
      - "5004:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseConnection=Server=sqlserver;Database=banreservas_security;User Id=SA;Password=Dionis12;Persist Security Info=True;Integrated Security=false;Connection Timeout=60;MultipleActiveResultSets=true;Encrypt=false;TrustServerCertificate=true"
      entrypoint: >
      bash -c "dotnet ef database update --context SecurityDbContext --project SecurityDomain/SecurityAPI/SecurityAPI.csproj"
    depends_on:
      - sqlserver
    networks:
      - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Dionis12"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
